version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    command: bundle exec rails s
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
